### PR TITLE
[TECHNICAL-SUPPORT] LPS-111656 User's categories and tags data are lost when saving on another tab.

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,

[LPS-111656](https://issues.liferay.com/browse/LPS-111656)
Based on the purpose of [this commit](https://github.com/brianchandotcom/liferay-portal/pull/65603/commits/46a73e989b1acdb5da016f7416cefffcc2b16967)

I decided to set the assetCategoriesId and assetTagNames to null in case we don't want to update them. I included the assetTagNames, as the issue was also reproducible with it.

As I know we investigated this issue and possible solutions from a variety of angles, I'd like to say this PR is focusing solely on the issue of losing **already saved** configuration in case we are saving on a different tab.
Saving **unsaved** configuration on an a different tab is currently considered a product limitation, and I think it should be introduced as a new feature on a different ticket.

Please review my changes,

Thanks

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
Since this issue is related to User & System Management rather than Frontend Infrastructure I'm forwarding it to the right SME ChrisKian#215

**Pull request closed without merging**
