### PR TITLE
[TS] LPS-83199 LayoutTemplate from theme cannot be applied on Layout

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi Antonio,

could you please check my fix.

Thanks, Roland

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test

**Comment by rolandpakai** [comment]
ci:reopen

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
Hi @rolandpakai,

All the layout management is related to WEM component rather than FEI.

In any case, I've been looking this PR and my main concern is the fact we are doing a partial revert of the changes we included in LPS-65845, to be more exact this commit: [https://github.com/liferay/liferay-portal/commit/01b2678957ee3fdba95ee17e3a418732a8d47e96](https://github.com/liferay/liferay-portal/commit/01b2678957ee3fdba95ee17e3a418732a8d47e96). Since there are no reproduction steps or tests in such LPS I'm not sure we are not breaking that fix.

For those reasons, I'm forwarding this PR to WEM SME dacousalr#50

Thanks,

**Comment by rolandpakai** [comment]
Hi @antonio-ortega,

thank you for informing me and forwarding to WEM

Regards, Roland

**Pull request closed without merging**
