### PR TITLE
LPS-110186 Use aui:select to make sure the langugae keys in the selection list are resolved

### PR DESCRIPTION
**Pull request by hudakl**
Hi Antonio,

Could you please review my solution proposal for LPS-110186?

Thank you,
Laci

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by hudakl** [comment]
Hi @antonio-ortega ,

I ran the sourceFormat and rebased the branch.

Thanks,
Laci

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
Hi @hudakl ,

Can you review the formatting issue, please?

Thanks.

**Comment by hudakl** [comment]
Hi @antonio-ortega ,

Sorry, I missed that.

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
brianchandotcom#86312

**Pull request closed without merging**
