### PR TITLE
LPS-112180 Refactor focus/blur handling

### PR DESCRIPTION
**Pull request by wincent**
@antonio-ortega: this is [your pull](https://github.com/wincent/liferay-portal/pull/231) with [one commit](https://github.com/antonio-ortega/liferay-portal/commit/a5b9120f98c9990d2dbf7e03b24510d3eb32086b) added on top.

### Changes

Based on:

https://github.com/wincent/liferay-portal/pull/231

I think there were a few of problems with that approach:

- Missing "]" at end of selectors.
- `blur()` would explode, because as soon as we remove the `[role="alert"]`, the `A.one()` call has nothing to find, will return `null` and we die calling `.setAttribute()` on `null`.

So, this commit makes a few changes:

- If we always pass `counterTextNode` into `_uiSetRemainingTime()`, we don't need to re-find the node inside that method.
- Rather than finding `[role="alert"]` anywhere in the document, scope the search more tightly by using `.closest()` and starting from the counter.
- Store the found alert in `this._alert` so that we can find it later on when restoring the `[role="alert"]`.

The remaining problem:

I am not sure whether `blur()` is the right place to restore the role. For example, if I have focus on the alert close button, and I tab to the "Extend" button, `blur()` will fire because the close button lost focus, and that bubbles (apparently; that seems non-standard to me, but maybe it is an AUI thing, because that's what I'm seeing when I test this). As a result, `[role="alert"]` gets added back and then removed again after 1 second.

Notes on YUI and "blur" bubbling:

- https://yuilibrary.com/yui/docs/event/focus.html (they fake it).
- https://developer.mozilla.org/en-US/docs/Web/API/Element/blur_event (it is not supposed to bubble).

So one final change, I make sure we only blur when the focus really leaves the entire notification, using `contains()` and `relatedTarget`. Still need to confirm that that is right: for example, when the alert shows, we remove `[role="alert"]` after one second; if you then tab out of the alert, we add back the `[role="alert"]`, and one second later, it gets removed again.

### Original message

Hi @wincent ,

Although previous fixed avoided losing the focus, we've realized about a new issue: Screen readers are reading the whole banner from the beginning with every update.

I've discussed the issue with @marcoscv-work and @eduardoallegrini and they thought the best way to fix this behaviour should be to hide the banner to our screen reader, i.e., removing role="alert" when we are focusing the banner.

Additionally, although it is not strictly needed, I've included an extra change within _uiSetRemainingTime function to update only the counter instead the whole banner.

### CODE REVIEW

**Comment by wincent** [comment]
So, about this:

> I am not sure whether `blur()` is the right place to restore the role. For example, if I have focus on the alert close button, and I tab to the "Extend" button, `blur()` will fire because the close button lost focus, and that bubbles (apparently; that seems non-standard to me, but maybe it is an AUI thing, because that's what I'm seeing when I test this). As a result, `[role="alert"]` gets added back and then removed again after 1 second.

I tested in VoiceOver. When you tab away from the alert, you do indeed hear the alert again after one second (but only once). I think the right behavior, then, might be to *not* re-add the role on `blur`, but rather, on *next* `focus`; ie. only when re-focusing, and with the same `relatedTarget` check to make sure that fake event bubbling doesn't destroy everything.

**Comment by wincent** [comment]
Ok, one more commit: https://github.com/antonio-ortega/liferay-portal/pull/113/commits/76599881abbea53385a52c9ce818040965b2fbef — with this, I think the experience is pretty good, at least in VoiceOver.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
@drakonux, @marcoscv-work — this is the PR that we talked about in the daily.

**Comment by antonio-ortega** [comment]
ci:forward

**Pull request closed without merging**
