### PR TITLE
[TS] LPS-98228

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @antonio-ortega  

the QA found an issue during the test, please check my fix.

Thanks, Roland

https://issues.liferay.com/browse/LPS-98228

Previouse PR: https://github.com/brianchandotcom/liferay-portal/pull/81200

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
Hey @rolandpakai ,

I haven't had the time for a deeper look into this pull request today. I'll try tomorrow.

To speed up the process, could you explain why this issue is only reproducible when creating a new web content but not when updating one?

Thanks in advance!

**Comment by rolandpakai** [comment]
Hi @antonio-ortega 

during my fix later i was able to reproduce it when updating a web content:

1. Open a Web Content which has more than one HTML field with content
2. Change one of the HTML field content
3. Drag n drop this HTML field

Actual behaviour: The original content is set back instead of the new one

I updated my comment on the LPP too.

Thanks, Roland

**Comment by antonio-ortega** [comment]
Hi @rolandpakai ,

Sorry because my question was misleading. Based on your new finding I'll ask it in a different way: Why this issue does not happen if you don't update one of the field contents?

Thanks!

**Comment by rolandpakai** [comment]
Hi @antonio-ortega 

In the ckeditor.jsp the the initData() is called which is calling the getInitialContent function because the ckEditorContent is null.

https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/ckeditor.jsp#L427-L429

(The ckEditorContent value is only set here: https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/ckeditor.jsp#L571)

In the getInitialContent function the data is set by the '<%= (contents != null) ? HtmlUtil.escapeJS(contents) : StringPool.BLANK %>'; which is the initial/original data set by the backend on the jsp.

https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/ckeditor.jsp#L133-L144

In my fix i retrieve the ckEditorContent value in the initData function before testing the value.

Thanks, Roland

**Comment by antonio-ortega** [comment]
Hey @rolandpakai ,

I'm not sure about this fix. Having a look at the code in the brand new recreateEditor function it looks like we are setting HTML before the editor is completely created. 

In fact, just for testing purposes (not a final solution), if I enclose editor.setHTML(html) within a timeout everything works fine.

I'd say the final solution would be managed in ddm_form.js in such a way that we are sure we are setting the HTML content once the editor is ready. What do you think?

Thanks.

Regards.

**Comment by antonio-ortega** [comment]
Hi @rolandpakai ,

Unless you have more questions about this topic I'm going to close this PR.

Thanks.

**Comment by rolandpakai** [comment]
Thanks @antonio-ortega 

Currently i dont have any question.
I will looking for a solution based on your suggestion.

Thanks again, Roland

**Pull request closed without merging**
