### PR TITLE
[TECHNICAL SUPPORT] LPS-116295 Ckeditor' dialog won't dynamically re-center on browser resize

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,

[LPS-116295](https://issues.liferay.com/browse/LPS-116295)

Please review my changes.

Thanks

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
Hey @NemethNorbert ,

Having a look at the LPP linked to this LPS I can see this is a regression bug introduced after fixpack-de-90-7010. Have you identified which changed caused this behavior?

Thanks.

Regards.

**Comment by NemethNorbert** [comment]
Hey @antonio-ortega,

Sorry I did not include this in the LPS.
The original root cause is: [LPS-107869](https://issues.liferay.com/browse/LPS-107869)
And it was fixed by: [LPS-111979](https://issues.liferay.com/browse/LPS-111979)
Now I'd like to improve upon the latter with dynamic re-center to resolve this feature loss.

I hope it answers everything.

Thank you

**Comment by antonio-ortega** [comment]
liferay-frontend#69

**Pull request closed without merging**
