### PR TITLE
[TECHNICAL SUPPORT] LPS-8711 Site roles are incorrectly assigned when they are selected from different pages

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hello @antonio-ortega ,

[LPS-87117](https://issues.liferay.com/browse/LPS-87117)
I introduced a null check on 'item', as it will be null if it`s hidden / it`s on another page. 
Because of the null check I had to change the const to var.

Please review it,
Thanks

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
Hi @NemethNorbert ,

Looks good to me. 

Please, amend the commit message to point to the right LPS and you can send it directly to Product Team (just cc me in the message).

And I think it's worth it to mention (in LPS or Github) the JS error you get when you try to select a role from the second page:
`search_container_select.js?browserId=other&minifierType=&languageId=en_US&b=7101&t=1541500982239:197 Uncaught TypeError: Cannot read property 'getData' of null
	at search_container_select.js?browserId=other&minifierType=&languageId=en_US&b=7101&t=1541500982239:197
	at Array.filter (<anonymous>)
	at component._getActions (search_container_select.js?browserId=other&minifierType=&languageId=en_US&b=7101&t=1541500982239:195)
	at component._notifyRowToggle (search_container_select.js?browserId=other&minifierType=&languageId=en_US&b=7101&t=1541500982239:254)
	at component.toggleRow (search_container_select.js?browserId=other&minifierType=&languageId=en_US&b=7101&t=1541500982239:136)
	at component._onClickRowSelector (search_container_select.js?browserId=other&minifierType=&languageId=en_US&b=7101&t=1541500982239:271)
	at component.<anonymous> (oop.js:403)
	at Y.Subscriber.delegate.notifySub [as _notify] (event-delegate.js:173)
	at Y.Subscriber.notify (event-custom-base.js:1335)
	at Y.CustomEvent._notify (event-custom-base.js:998)`

**Pull request closed without merging**
