### PR TITLE
[TECHNICAL SUPPORT] LPS-83318 Sign in Portlet is maximized upon failed login, even when a full sized sign in portlet is on the page

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey @antonio-ortega ,
LPS:
[LPS-83318](https://issues.liferay.com/browse/LPS-83318)
SME request:
[LPP-30768](https://issues.liferay.com/browse/LPP-30768)

The issue is we maximize the login portlet upon failed login attempt, when there is a full sized log in portlet on the page.In that scenario, the failed login attempt should be displayed in the full sized login portlet without maximizing it to full screen.
See the SME request for further details regarding the expected and current behavior.
Please review the PR.

Thanks,

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test

**Comment by antonio-ortega** [comment]
Hi @NemethNorbert ,

Login Portlet belongs to security team, so I'd recommend you to send this PR to them.

Thanks,

**Comment by NemethNorbert** [comment]
Hey @antonio-ortega ,
I sent you this PR, because I think it`s a UX question.
However I can still send this PR to them.

**Comment by antonio-ortega** [comment]
Hi @NemethNorbert ,

Thanks for your explanation, however in these cases is convenient to distinguish between Frontend and Frontend Infrastructure. Although I appreciate it, not all the frontend issues should go through Frontend Infrastructure SME, basically because every team is responsible of the frontend side of their components and they are the people who better know the code and possible side-effects on any change.

I'd recommend you to have a look at this [Grow Page](https://grow.liferay.com/share/Support+guidance+for+cross-cutting+components).

Thanks!

**Comment by lipusz** [comment]
https://github.com/antonio-ortega/liferay-portal/pull/52

**Comment by lipusz** [comment]
https://github.com/lipusz/liferay-portal/pull/232

**Pull request closed without merging**
