### PR TITLE
[TS] LPS-113325

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @antonio-ortega 

The changes are in the user-admin-web and frontend-js-aui-web::util.js
If you think you are not the rigth reviewer please feel free to forward this PR.

This issue is related to adding and removing assets in the User's Regular Roles, Organization Roles, Site Roles, Asset Library Roles, Sites, User Groups, Organizations.

**Initial state:**
Adding to the assets was handled by the selectEntity::disableSelectedAssets,
removing from the assets was handled by a sync event, fE: regularRoleSyncEntitiesEventName.
But when performing a search in the asset list the searhContainer was not updated by this functions.

**Fixed state:**
Now the selectEntity::syncAssets handles both the adding and removing functionalities.
And additionally i added a searchContainerUpdateDataStore function which handles the groupId.
 
https://issues.liferay.com/browse/LPS-113325

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
Hi @antonio-ortega 
could you please review my PR?
Thanks, Roland

**Comment by antonio-ortega** [comment]
Hi @rolandpakai ,

I'm afraid I'm not the person to make a decision about this pull request. Since it is entirely related to User&System management you should contact their SME to ask for review. You can check SME List in this [page](https://grow.liferay.com/people?p_p_id=com_liferay_wiki_web_portlet_WikiPortlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&_com_liferay_wiki_web_portlet_WikiPortlet_struts_action=%2Fwiki%2Fview&_com_liferay_wiki_web_portlet_WikiPortlet_pageResourcePrimKey=94183&p_r_p_http%3A%2F%2Fwww.liferay.com%2Fpublic-render-parameters%2Fwiki_nodeName=Grow&p_r_p_http%3A%2F%2Fwww.liferay.com%2Fpublic-render-parameters%2Fwiki_title=SME+Master+List).

Apart from that, based on my experience trying to review this case, I'd like to clarify a few points to make it easier for next reviewer:

- Although [LPS-113325](https://issues.liferay.com/browse/LPS-113325) is labelled as 'Master' as the only affected version, the issue is reproducible in other branches as well.

- In [LPS-113325](https://issues.liferay.com/browse/LPS-113325) you pointed as a wrong current behavior "_Indeed, if the page is refreshed, the deleted role re-appear._" As far as I understand there is no auto-save functionality in this case, in fact, we have a 'Save' button at the bottom of that page to manually persist changes. Anyway, this point should be clarified by User&System MGMT team.

- The list of places where this issue is reproducible listed in [LPS-113325](https://issues.liferay.com/browse/LPS-113325) is wrong. As an example, in Membership -> Sites there is no 'Choose' button, so the issue is not reproducible.

- In general, I can see we are following two different patterns when editing user information, sometimes even within the same tab, as it happens in Memberships tabs. In that case:

1. For user groups we have 'Choose' button which is enable/disable through Javascript after the modal is loaded. 
2. However, for Sites and Asset Libraries, there no 'Choose' button and we can choose whatever we want, and the selection will be managed later to avoid duplicated information. This approach is similar to what we do in other places, like Related Assets in Web Content, Blogs, D&M, etc. 

IMHO, this could be considered as an inconsistent behavior by the customers.

I personally think we should, first of all, make a decision about which pattern we want to follow while editing user information, and then work in make it consistent and be sure it is working for all the cases, as well, after using search in management toolbar.

As I said in the beginning, you can forward this issue to the right SME who can give you a better answer than me since I don't know all the use cases for user's management.

Thanks.

Regards.

**Comment by rolandpakai** [comment]
Thank you for your comment @antonio-ortega

**Pull request closed without merging**
