### PR TITLE
[TECHNICAL SUPPORT] LPS-85974 Child pages may disappear if the mouse is not moved quickly enough

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey @antonio-ortega , @jbalsas,

[LPS-85974](https://issues.liferay.com/browse/LPS-85974)
I improved on the solution and now the 'showNavigationMenu' event is without delay while still clearing the setTimeOut to avoid closing the dropdown from a delayed 'hideNavigationMenu' event.

Please review it.
Thanks,

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
Hi @NemethNorbert ,

Thanks for resend this PR taking into consideration the comments mentioned [here](https://github.com/julien/liferay-portal/pull/69), even though I'm not completely sure whether we are accomplishing all the requirements, I'd like to ask you to fix SF issue and resend this PR to @julien, from product team, so he can evaluate it.

Thanks in advance.

**Comment by NemethNorbert** [comment]
resent https://github.com/julien/liferay-portal/pull/75

**Pull request closed without merging**
