### PR TITLE
[TS] LPS-121651 Navigation Errors with Inactive Sites

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @antonio-ortega 

the site navigation are used at the following places:
1. Site administration (Control Panel > Sites)
2. Site Item Selector (Compass icon in Product Menu)
3. My Sites Portlet (list of sites in 'My Dashboard)

For further testing the Inactive Request Handler should be checked at Control Panel > Configuration > System Settings > Infrastructure > Inactive Request Handler and site (My site) should be deactivated.

In the **1st** case the site navigates to the site admin web, we dont need to add the data-senna-off atribure.

In the **2nd** case the site navigates to the http://localhost:8080/web/my-site and the "This site is inactive. Please contact the administrator." page loads. Based on my tests after refreshing the page and navigating back i still see the inactive message. I implemented the same fix on 70x and on that branch it works for me. - Could you please check this on your side?

In the **3rd** case the page opens in a new browser tab, we dont need here neither the data-senna-off atribure.

Beside that i added the dataSennaOff attribute to the vertical-card, user-vertical and icon-vertical card taglibs which will be used on the 71x and 70x branches but the code will be more consistent among branches.

See details on the PTR:
https://issues.liferay.com/browse/PTR-1968?focusedCommentId=2279647&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2279647

https://issues.liferay.com/browse/LPS-121651

### CODE REVIEW

**Comment by antonio-ortega** [comment]
Hi @rolandpakai ,

If I've understood your message this pull request is not working. It's what I've got from:

> Based on my tests after refreshing the page and navigating back i still see the inactive message

Am I right?

If that's the case, it does not make any sense to send a pull request. I'd prefer you to reopen PTR-1968, label it as _Solution guidance_ and you can explain there your analysis and the differences you can see between 7.0.x and Master and why you think is working in one branch but not in other, even if you test your solution in intermediate branches like 7.1.x or 7.2.x because that could help. I mean, just to explain your analysis, as usual.

Thanks.

Regards.

**Comment by rolandpakai** [comment]
Yes, the same solution is working on 70x but not on master...
(I added data-senna-off="true" to the aui:a links)

I thought the issue is only on my side...

**Comment by antonio-ortega** [comment]
In that case and as I said above, you can reopen the PTR providing the information I mentioned and we can work over there. That's the place for a solution guidance. Please, correct me if I'm missing something but there's no reason to think the code is not working in your end is magically going to work in my end.

Anyway, if all what you want is someone else to test your changes, I'm sure some TS next to you can give you a hand to test your branch.

Closing this pull request now since the code is not working.

**Comment by rolandpakai** [comment]
Well, i believe in Magic  :)

d820481ef14b1cd2a16ff4e7660deb5f

PS: I will write on the PTR - Thanks

**Pull request closed without merging**
