### PR TITLE
LPS-122099 Add a unique aria-label to make landmarks distinguishable

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @antonio-ortega 

could you please check my change?
I added area-label attribute to the nav tag to make landmarks distinguishable.

Thanks, Roland

https://issues.liferay.com/browse/LPS-122099

### CODE REVIEW

**Comment by antonio-ortega** [comment]
Hi @rolandpakai ,

Just a couple of quick questions about this pull request:

1. If our Classic Themes [already makes use](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-theme/frontend-theme-classic/src/templates/portal_normal.ftl#L17) of that taglib in its portal_normal.ftl, why do we need to create a new theme to reproduce this issue?
2. Since there are different possibilities to solve most of the accessibility issues, could you explain the reason why you choose to add an **aria-label** attribute to our navbar to fix this issue?

Thanks.

Regards.

**Comment by rolandpakai** [comment]
Hi @antonio-ortega 

thanks for the quick review.

1. I didnt checked the classic theme, but if it use the quick-access taglib than not needed to use the dummy theme.
2. I followed the axe Analyze result notes and the more info page about the issue.

> Issue description
> 
> Landmarks must have a unique role or role/label/title (i.e. accessible name) combination
> 
> More info
> Element location
> 
> #jhfi_quickAccessNav
> 
> Element source
> 
> &lt;nav class=&quot;quick-access-nav&quot; id=&quot;jhfi_quickAccessNav&quot;&gt; &lt;h1 class=&quot;hide-accessible&quot;&gt;Navigation&lt;/h1&gt; &lt;ul&gt; &lt;li&gt;&lt;a href=&quot;#main-content&quot;&gt;Skip to Content&lt;/a&gt;&lt;/li&gt; &lt;/ul&gt; &lt;/nav&gt;
> 
> To solve this violation, you need to...
> Fix the following:
> 
> The landmark must have a unique aria-label, aria-labelledby, or title to make landmarks distinguishable
> Related node:
> 
> #ouom_quickAccessNav
> 
> More info: https://dequeuniversity.com/rules/axe/4.0/landmark-unique?application=AxeChrome

Thanks, Roland

**Comment by antonio-ortega** [comment]
Hi @rolandpakai ,

About the first point, I'd truthfully appreciate if you can test this with Classic Theme and in case this is reproduced, then update LPS with the proper and simpler reproduction steps. This way we are making the job easier for next reviewers and QA team.

About the second point, we need to keep in mind the specification when we are solving accessibility issues rather than some vendors tools because they can return different results for the same markup. And we also can double check against the [W3C official validator](https://validator.w3.org/). As well, when reporting accessibility issues would be recommendable to mention which section of the specification we are trying to achieve with the new change, so it is easier for reviewer to check the possible techniques.

Said that, I can understand your change, it is needed and it is going to be enough for an accessibility validator, but is it accessible? If someone using a screen readers listen to something like "abdc_quickAccessNav", are they going to know what will happen when click on that link?

We need to pass accessibility validators to meet our commitments but we always need to keep in mind our first goal is being accessible, so we should include a clear message of what is about that navigation menu.

Thanks.

Regards.

**Comment by rolandpakai** [comment]
Hi @antonio-ortega 

i tested with the classic theme but the axe tool not lists the nav tag related landmarks issue.

Regarding the accessibility message whats your suggestion? We should remove the randomNamespace?

Thanks, Roland

**Comment by antonio-ortega** [comment]
Hi @rolandpakai ,

Can you check why this issue is not happening with Classic Theme but it is with custom themes? 

About the label, if we remove the randomNamespace, then the screen reader is going to say "quickAccessNav", would you understand the purpose with that description? Have a look at that navbar, see what is for and I'm sure you can pick a good message for it.

Thanks.

Regards.

**Comment by rolandpakai** [comment]
Hi @antonio-ortega 

I changed the area-label to Quick Links.

And I (with Alfonso) checked the classic theme but we where not able to find out the reason why not lists the axe the nav landmarks, but i tryed the WAVE extension and that gave us a better results and found the quick-access NAV element in the classic theme too.

image

Thanks, Roland

**Comment by alfonsocrisci** [comment]
Hi @antonio-ortega , it looks I found the reason why the error is triggered on a page with custom theme and not on one having the Classic Theme. On the custom theme page, there is this extra markup:

`<nav class="sort-pages modify-pages" id="navigation" role="navigation">`

This is not present on a page with Classic Theme. The whole story reconnects to this: https://github.com/department-of-veterans-affairs/va.gov-team/issues/4215:

> Using the <nav> element will automatically communicate a section has a role of navigation. If at all possible, prefer using it instead.
> 
> If there is more than one navigation landmark role or
> element in a document, provide a label for each landmark. This label will allow an assistive technology user to be able to quickly understand the purpose of each landmark.
> 
> The role="navigation" added to the div id="vetnav" conflicts with the nav element.
> 
> Recommend using aria-label to distinguish between the main and subnav navigation.

So, it looks, on the page with the custom theme, the tool finds both:

`<nav class="quick-access-nav" id="jhfi_quickAccessNav"> <h1 class="hide-accessible">Navigation</h1> <ul> <li><a href="#main-content">Skip to Content</a></li> </ul> </nav>`

and

`<nav class="sort-pages modify-pages" id="navigation" role="navigation">`

and requests to flag the first to make it unique.

To proof-check it, on the page with the custom theme, I removed `<nav class="sort-pages modify-pages" id="navigation" role="navigation">` from the DOM and repeated the Axe check: the flagged issue with "All page content must be contained by landmarks" disappeared.

**Comment by antonio-ortega** [comment]
Hi @alfonsocrisci ,

Thanks for the analysis. It all makes sense now about the differences between a custom theme and classic theme. 

Coming back to the pull request there is something I'm missing right now. The quote you are mentioning says:

> If there is more than one navigation landmark role or element in a document, provide a label for **each** landmark.

They say to provide a label for each landmark, not only for the first one in the DOM, so shouldn't be more correct to find where we are including 
`<nav class="sort-pages modify-pages" id="navigation" role="navigation">`

and add `aria-label` attribute as well?

What do you think, @rolandpakai ?

Thanks.

Regards.

**Comment by rolandpakai** [comment]
Hi @antonio-ortega 

The <nav class="sort-pages modify-pages" id="navigation" role="navigation"> is comming from the navigation.ftl from the frontend-theme-unstyled here: https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-theme/frontend-theme-unstyled/src/main/resources/META-INF/resources/_unstyled/templates/navigation.ftl#L1

Yes, i think we can add the aria-label on that nav element too.
(I you check the next ul element there an aria-label used too: https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-theme/frontend-theme-unstyled/src/main/resources/META-INF/resources/_unstyled/templates/navigation.ftl#L2)

Thanks, Roland

**Comment by rolandpakai** [comment]
I force-pushed the PR with the changes.

**Comment by antonio-ortega** [comment]
liferay-frontend#432

**Pull request closed without merging**
