### PR TITLE
[Technical-Support] LPS-119036 Image placeholder and arrow in pagination issue with rtl view

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,
[LPS-119036](https://issues.liferay.com/browse/LPS-119036),

I implemented your suggestion regarding the icons and I had to change the css selector for master. 
Please review my changes

Thanks,

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
Hey @antonio-ortega ,

Could you help me out with the SF error? On my local machine
`gradlew formatSource` runs successfully and I don't see any issue looking trough the change manually.

**Comment by antonio-ortega** [comment]
Hi @NemethNorbert ,

**The source formatter error** is about a missing line at the bottom of _vertical_card.scss file.

**Regarding the solution about the arrows**, I'm not an expert in arabic but I'd say after this change we are showing the message "Previous page" in the tooltip to move forward and "Next Page" to move backwards.

**Regarding the solution about cards alignment**, if I compare RTL and LTR I'd say the don't have the same alignment:
Screenshot 2020-08-14 at 08 39 44

Can you review this and resend, please?

Thanks.

Regards.

**Comment by NemethNorbert** [comment]
Resent https://github.com/antonio-ortega/liferay-portal/pull/129

**Pull request closed without merging**
