### PR TITLE
LPS-118907 align search icon with wrapper

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,
[LPS-118907](https://issues.liferay.com/browse/LPS-118907),

I know it's not frontend-infra, but a css change inside the _portal-search-web_ module, however the Search SME is on a longer PTO and I'd be interested if I made the right fix from a frontend perspective.

Please review my changes.

Thanks,

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
Hi @NemethNorbert ,

Since all what you are asking is just an opinion, I can summarise some points about this pull requests:

- First of all, I wouldn't include the new CSS class in main.scss file. We are using that one only for imports, so if you want to inlclude a new CSS class should be inside one of the imported files, or create a new one and import it from main.scss.

- If the expected behavior is what is defined in LPS

> The search button should come inside the search box

These changes are accomplishing such goal. However, if you compare it with the new Search Bar, it does not seems to follow our style guidelines yet:

LPS-118907-Screenshot

Old search widget is shorter and the magnifying glass is not integrated into it yet, it has its own button (next to the bar) that becomes more obvious when you hover it.

What I mean is if the goal is just to move the button inside the bar, you got it. If the goal is to make the old widget look like the new one, we still need some adjustments.

The positive side of trying to make them look the same is that we don't need to create new CSS class, we can reuse what we already have. The downside is that we need a few more changes in view.jsp to reorder a bit the HTML output and to use the new CSS classes.

My opinion from a frontend perspective is that I'd try to make both portlets looks similar, but maybe that's not what Search Team wants, so you can forward this pull request to Search team and see what they think.

Thanks.

Regards.

**Comment by NemethNorbert** [comment]
Hey @antonio-ortega,

Thanks for the review, I make some improvements before I forward it 👍

**Pull request closed without merging**
