### PR TITLE
[TECHNICAL SUPPORT]LPS-82998 Unable to save configuration for pages with Freemarker layout templates

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey @antonio-ortega ,

[LPS-82998](https://issues.liferay.com/browse/LPS-82998)

Please review the PR,

Thanks

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by NemethNorbert** [comment]
ci:reopen

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
Sent to izaera#57

**Pull request closed without merging**
