### PR TITLE
LPS-109291 Empty value attribute prevents being WCAG 2.1 compliant for accessibility

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,

Based on [PTR-1510](https://issues.liferay.com/browse/PTR-1510), I sent the solution for review.
[LPS-109291](https://issues.liferay.com/browse/LPS-109291)
Thanks,

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
brianchandotcom#85316

**Pull request closed without merging**
