### PR TITLE
LPS-123371 Handle if selectedData is undefined

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @antonio-ortega 

The LPS-123371 is reproducable only on 72x, because the Liferay.Util.selectEntity is used in 72x only, 
on master/73x we started to use the Liferay.Util.openSelectionModal.

On master we are using the Liferay.Util.selectEntity only at the ItemSelectorDialog.es.js
https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/ItemSelectorDialog.es.js#L62-L71

I would like to send the fix to master too, becuase the Liferay.Util.selectEntity is still used,
and we still have the Liferay.Util.selectEntity in the util.js

The case:  if the selectedData is undefined than the disabled value will be undefined too.
The fix:  if the selectedData is undefined, than the !!selectedData will be false, and the disabled value will be false too. 

Thanks, Roland

https://issues.liferay.com/browse/LPS-123371

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
Hey @rolandpakai ,

I've been having a look at this case and I'm not sure whether this is the right fix.

If you follow the same steps in Bookmarks (which also uses Liferay.Util.SelectEntity()) this issue is not reproducible. That leaded me to think the issue could be in Documents&Media rather than in Liferay.Util.SelectEntity() itself.

So, I just tried a different approach that you can see [here](https://github.com/antonio-ortega/liferay-portal-ee/commit/4797d3a683a07d3b61da83eadd65923167154bdf) and it worked. But even with that solution there are two user interface issues that I think should be answered by Lexicon & Lima Teams:

- In my solution, the current folder is shown as disabled because in my opinion it does not make sense to move a file to the same folder where it already belongs to. That's just muy opinion, they should confirm that's the expected behavior.

- With the current implementation, before this LPS, even when the button is disabled you still can click in the whole row because every element in the row is a link. I think this is a design problem, because no matter what we do with the button (enable or disable) you can always follow the links. I think they should clarify these point as well. In my opinion we should remove those links or disabling them at the same time than the button, but someone from Lexicon & Lima could help you with that.

Thanks.

Regards.

**Comment by rolandpakai** [comment]
Hi @antonio-ortega 

thanks for sharing the different approach. I tested it and it works for me too.
Regarding the user interface issues 

1. Disabling buttons is valid, and it is reproducable on master too (Disabling button works in fE "Select Regular Role" in the User General tab, so i think it should work the same way in Select Destination Folder too)
2. Clickable row items instead of just the folder name is valid too and it is reproducable on master too

Both issues are reproducable on master too,
and implementing your 72x fix (https://github.com/antonio-ortega/liferay-portal-ee/commit/4797d3a683a07d3b61da83eadd65923167154bdf) on master solves the 1. issue too.

I will open a PTR for the Lexicon  

I also updated the https://issues.liferay.com/browse/LPS-123371 description too,
and i set the master and 73x too for the affected version.

Thanks, Roland

**Pull request closed without merging**
