### PR TITLE
[TECHNICAL-SUPPORT] LPS-110753 Liferay sidebar is visible in print preview

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,

[LPS-110753](https://issues.liferay.com/browse/LPS-110753)

I added the same .hidden-print css code to _generic_portal.scss, that is available trough bootstrap and we used on 7.0

Please review it, thanks!

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
Hey @antonio-ortega,

I can't get rid of the SF error. I run formatSource locally and it print that it fixed the file, however there is nothing to commit. Repeating this step yields the same result. What can be the problem?

**Comment by antonio-ortega** [comment]
marcoscv-work#312

To solve the formatting issue locally, run yarn checkFormat in your module and it would get solved.

**Pull request closed without merging**
