### PR TITLE
[TS] LPS-112494

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi  @antonio-ortega 

could you please check my changes and push it forward?

Thanks, Roland

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
https://github.com/wincent/liferay-portal/pull/246

**Pull request closed without merging**
