### PR TITLE
[TS] LPS-105881

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-105881](https://issues.liferay.com/browse/LPS-105881)

Hi Antonio,

I am sending this to you as suggested by Tibor Lipusz is on https://github.com/topolik/liferay-portal/pull/824. I hope you can review it.

Thank you,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
jbalsas#2088

**Pull request closed without merging**
