### PR TITLE
[TECHNICAL SUPPORT] LPS-89615 Minifier is trying to minify already minified files

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey @antonio-ortega,

[LPS-89615](https://issues.liferay.com/browse/LPS-89615)

Please review my changes.

Thanks,

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
Sent to jbalsas#1616

**Pull request closed without merging**
